### ISSUE TITLE
Add a git repo "target" class

### ISSUE THREAD

**Issue by austinpray** [roots/wordpress-packager#23]
@TangRufus you want to handle porting those git repo creation classes from your repo over to this one?

## Context

Right now we have [Release Sources][]. A release source is totally open-ended but the bottom line is it grabs some remote data and turns it into a [WordPressPackageRepository][]. Right now we have [WPDotOrgHTML][] as a release source, which fetches the download page and parses it into a repo. Soon I will have `WPGitHubAPI` or something that builds a repo from [much like the old one does](https://github.com/roots/wordpress/blob/f9fdc46d25a3d035be4ab1bb88fe3ba931d51de7/bin/update-wp-releases.php) but I will implement it cleaner.

So have "sources" now we need "targets". One of these targets has to be a git repo since we need to build roots/wordpress and other repos like it. You have a `Build` class [over here](https://github.com/ItinerisLtd/wordpress-packager/blob/6442dd1370af87db69febcc90ae3a5f038b4a8c8/src/Build.php) that has some useful git repo management logic we can duplicate over here to create a "target" class.

## Suggestions

- a "target" class should probably just work directly with [WordpressPackageRepository][] classes as input.
- the git repo should be configurable to a remote repo or local filesystem repo. Basically any valid git remote
- I don't want this class to rely on `Composer\IO\IOInterface` or anything like that, it should just be a generic class that doesn't really understand that it's running on the CLI. If we need logging we can use https://www.php-fig.org/psr/psr-3/ and https://github.com/Seldaek/monolog. Error messages should be exceptions
- `Symfony\Component\Filesystem\Filesystem` seems like a fine dependency :+1: 
- `Cz\Git\GitRepository` seems fine :+1: 

## Reference

Also [here is the old repo updater script for refrence](https://github.com/roots/wordpress/blob/f9fdc46d25a3d035be4ab1bb88fe3ba931d51de7/bin/update-repo.php).

[Release Sources]: https://github.com/roots/wordpress-packager/blob/124058f977e001f002f83a00fd6ae57eb2a6b49c/src/WordPressPackager/ReleaseSources/SourceInterface.php
[WordPressPackageRepository]: https://github.com/roots/wordpress-packager/blob/124058f977e001f002f83a00fd6ae57eb2a6b49c/src/WordPressPackager/WordPressPackageRepository.php

**Comment by austinpray** [comment]
updated the OP with more clarity

**Comment by TangRufus** [comment]
Sounds good!

In my version, I use `composer build` as an entry point. What is the "entry point" you having in mind?

**Comment by austinpray** [comment]
Well we should build the classes such that they don't really have any idea where they are being used. The entrypoint ideally will just be something like https://github.com/austinpray/ItinerisLtd-wordpress/blob/93c35e4aeef28a134b936f4acace2951480d4343/bin/generate-satis-json.php

1. require autoloader
2. run the "CLI" entrypoint function

so it could totally end up being something like https://github.com/austinpray/ItinerisLtd-wordpress/blob/93c35e4aeef28a134b936f4acace2951480d4343/composer.json#L58-L59

**Comment by TangRufus** [comment]
see #39
