### ISSUE TITLE
run tests on circleci

### ISSUE THREAD

**Issue by austinpray** [roots/wordpress-packager#3]
We have two test commands: 
- `composer test` <- default test suite 
- `composer test:e2e` <- end-to-end tests (none right now)

Can prolly just steal https://github.com/ItinerisLtd/wordpress-packager/blob/d56ca71f450349fb8e910e12be888cc392cc1aa1/.circleci/config.yml

@TangRufus wanna do this since you are already a pro at circleci?

**Comment by TangRufus** [comment]
i am far from a pro. but challenge accepted.

besdies `composer install`, do you need anything installed (e.g: selenium, chrome, etc) for the e2e tests?

**Comment by TangRufus** [comment]
Do we need to run `curl -s "https://wordpress.org/download/releases/" > repo-pass-1.json` on CircleCI daily/weekly to ensure our HTMl praser is up to date with wp.org?
Or, it would be the future e2e test?

**Comment by austinpray** [comment]
@TangRufus the e2e test will check whatever is live so we will be covered there

We could def have the unit tests self-update in the future though. e2e tests will have us covered as far as ensuring compat with the live html though.
