### ISSUE TITLE
Add code coverage to CI

### ISSUE THREAD

**Issue by austinpray** [roots/wordpress-packager#4]
blocked by #3 

https://github.com/roots/wp-config has a decent coverage system

- https://github.com/roots/wp-config/blob/2ae55cc8fd4d3a6ce463cbfcfce9a01e2e9e77e5/phpunit.xml#L16-L20
- https://github.com/roots/wp-config/blob/2ae55cc8fd4d3a6ce463cbfcfce9a01e2e9e77e5/Makefile#L8-L9
- https://github.com/roots/wp-config/blob/2ae55cc8fd4d3a6ce463cbfcfce9a01e2e9e77e5/Makefile#L56-L58

I use coveralls for php: https://coveralls.io/github/roots/wp-config?branch=master

It's decent but I could be convinced to use something else. I feel like there's gotta be some new hotness that I don't know about.

**Comment by austinpray** [comment]
I think ima use codeclimate instead. They gave me a sticker once

**Comment by TangRufus** [comment]
How did you send coverage reports to codeclimate?
Run commands locally?

**Comment by austinpray** [comment]
Yeah I ran this https://github.com/roots/wordpress-packager/blob/a7a2bf2916c261559b21604f4bc565b8960273a6/Makefile#L38-L43 locally to test

but they were also sent from circleci later https://circleci.com/gh/roots/wordpress-packager/5

**Comment by TangRufus** [comment]
closed by #9
