### ISSUE TITLE
Require PHP extensions

### ISSUE THREAD

**Issue by LeoColomb** [roots/wordpress-packager#40]
Would be great to explicitly require PHP extensions used by WordPress in packages.

They are listed here: https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions

No need to specify versions: https://getcomposer.org/doc/01-basic-usage.md#platform-packages

Ref: https://github.com/ItinerisLtd/wordpress-packager/issues/15

**Comment by austinpray** [comment]
👍 

Just to be clear:
- php extensions that, if missing, will cause WordPress to not work at all should be under the “require” key https://getcomposer.org/doc/04-schema.md#require
- php extensions that enable additional functionality inside WordPress or speed things up go under the “suggest” key https://getcomposer.org/doc/04-schema.md#suggest

For instance ext-json is used extensively by WordPress. However: if this extension is missing WordPress includes a polyfill and everything still works fine. This means ext-json goes under the “suggest” key.

**Comment by austinpray** [comment]
@TangRufus I merged https://github.com/roots/wordpress-packager/pull/41

Seems backwards compatible and adds value. In the future we might need to check wordpress version and change suggestions based on new/removed deps
