### ISSUE TITLE
Pathspec failure on `git rm`

### ISSUE THREAD

**Issue by swalkinshaw** [roots/wordpress-packager#483]
https://github.com/roots/wordpress-packager/runs/6186419048?check_suite_focus=true

@LeoColomb this looks to be failing here https://github.com/roots/wordpress-packager/blob/2f1e7ed756bad215c5f1a1c71ca89c59185fb06e/src/Target.php#L69

> fatal: pathspec '.' did not match any files

Leads me to believe that the checkout on the line before it isn't completely working. `git checkout --orphan idontexist` will create a new branch due to `--orphan` so maybe that's just silently failing?

1. checkout a non existent branch
2. git switches to new branch
3. `git rm --cached -r .` fails because there's no files

This could be a setup problem on this workflow or with the secrets. I created a new https://github.com/roots/wordpress-full empty repo.

**Comment by swalkinshaw** [comment]
🤦 added a README to the repo to fix that issue. I might add something to prevent that 

Here's the next failure I'm debugging: https://github.com/roots/wordpress-packager/runs/6186759509?check_suite_focus=true

**Comment by LeoColomb** [comment]
@swalkinshaw Yes, quite out of lucky, we are in the week where `czproject/git-php` is breaking the builds: https://github.com/czproject/git-php/issues/77#issuecomment-1110648631

**Comment by swalkinshaw** [comment]
Thanks @LeoColomb 

Action ran successfully: https://github.com/roots/wordpress-full

**Comment by LeoColomb** [comment]
Yes!
And the tags are well pushed to the repo: https://github.com/roots/wordpress-full/tags 🥳

**Comment by swalkinshaw** [comment]
@LeoColomb sorry just re-using this issue to ask two other questions:

1. does the `trunk` branch need to be manually setup to offer nightly?
2. Packagist requires a `composer.json` file in the default branch to add a package. I noticed that one of yours still has one, but the other two had it deleted. Did you just have it there to meet the Packagist requirements then it's safe to delete?

**Comment by LeoColomb** [comment]
2. I still don't know if it's a good idea to delete it after initial Packagist submission. It might create some issues if the README get updated for example. But again I'm still unsure.
Nightlies being shipped for "full" variant only is the reason why I deleted the others.

<small />

1. Depending of previous point' answer, you can use the main branch to store the "nightly" `composer.json` and then resolve both concerns. The name `trunk` is just to match WordPress ecosystem expectations, but this follows opinion and nothing else.

---

**Comment by swalkinshaw** [comment]
https://packagist.org/packages/roots/wordpress-full 

I added the "nightly" `composer.json` to `main`
