### ISSUE TITLE
Test \Roots\WordPressPackager\Build (e2e tests)

### ISSUE THREAD

**Issue by TangRufus** [roots/wordpress-packager#56]
Test \Roots\WordPressPackager\Build (e2e tests)

Follow up https://github.com/roots/wordpress-packager/pull/39

* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)

**Comment by LeoColomb** [comment]
Closing this one per https://github.com/roots/wordpress-packager/pull/406.
That significant refectory moved most of the testable surface to classes.
An E2E test is still possible on the very command line script, but it looks like to be a bit overkill and costs more than it helps for the maintenance.
