### ISSUE TITLE
Accept license author name as build command arguments

### ISSUE THREAD

**Issue by TangRufus** [roots/wordpress-packager#59]
Accept license author name as build command arguments

https://github.com/roots/wordpress-packager/blob/a0e080bd7065ac6394a334bc9bb586fb079fa507/src/WordPressPackager/License.php#L16

Follow up https://github.com/roots/wordpress-packager/pull/39

* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)

**Comment by LeoColomb** [comment]
Closing via #406
